/* Capa adicional de WebPocket: registro mínimo, cliente y administración. */
(function () {
  state.auth = null;
  state.account = null;
  const basePanel = window.renderPanel;
  const baseBind = window.bind;
  const readDataUrl = (file) => new Promise((resolve, reject) => {
    if (!file) return reject(new Error("Adjunta el comprobante Yape."));
    if (file.size > 15 * 1024 * 1024) return reject(new Error("El archivo supera 15 MB."));
    const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = () => reject(new Error("No se pudo leer el archivo.")); reader.readAsDataURL(file);
  });
  const formatOptions = () => state.formats.map(f => `<option value="${esc(f.id)}">${esc(f.nombre)}</option>`).join("");
  const notice = (id, value, kind = "") => { const node = app.querySelector(id); if (node) { node.className = `message ${kind}`; node.textContent = value; } };
  const send = async (data) => edge({ ...data, session: state.auth?.session });

  window.registerSheet = function () {
    const f = state.formats[0] || FALLBACK_FORMATS[0];
    return `<aside class="overlay open"><section class="sheet"><div class="sheet-head"><div><span class="eyebrow">REGISTRO INICIAL</span><h3>Abre tu WebPocket</h3></div><button class="close" data-close>×</button></div><p>Primero crea tu acceso, elige periodo, formato y colores. Completarás datos personales o del negocio desde tu sesión después de la activación manual.</p><form id="quick-register-form" class="form"><div class="grid2"><div class="field"><label>Usuario</label><input name="usuario" placeholder="Crea tu usuario"></div><div class="field"><label>Clave</label><input name="clave" type="password" placeholder="Crea tu clave"></div></div><div class="grid2"><div class="field"><label>Tipo</label><select name="tipoPerfil"><option value="CV">CV personal</option><option value="NEGOCIO">Negocio</option></select></div><div class="field"><label>Periodo</label><select name="periodoMeses"><option value="3">3 meses</option><option value="6">6 meses</option><option value="12">1 año</option></select></div></div><div class="field"><label>Formato</label><select name="formatoId">${formatOptions() || `<option value="${esc(f.id)}">${esc(f.nombre)}</option>`}</select></div><div class="colors"><div class="field"><label>Color principal</label><input name="principal" type="color" value="${esc(f.color_principal || '#38bdf8')}"></div><div class="field"><label>Color secundario</label><input name="secundario" type="color" value="${esc(f.color_secundario || '#a78bfa')}"></div><div class="field"><label>Color de fondo</label><input name="fondo" type="color" value="${esc(f.color_fondo || '#07101e')}"></div></div><div class="price-box"><span class="eyebrow">PAGO POR YAPE</span><strong id="quick-total">S/ 40.00</strong><p id="quick-detail">CV por 3 meses. Yape: 967 188 120.</p></div><div class="field"><label>Comprobante Yape</label><input name="receipt" type="file" accept="image/*,.pdf"></div><p class="message">El registro se activa solo cuando se adjunta el comprobante. El administrador revisará el pago y recién entonces podrás completar tu perfil y obtener tu QR.</p><p id="quick-register-message" class="message hidden"></p><button class="submit">Registrar solicitud</button></form></section></aside>`;
  };

  window.loginSheet = function () {
    return `<aside class="overlay open"><section class="sheet"><div class="sheet-head"><div><span class="eyebrow">ACCESO</span><h3>Cliente o administrador</h3></div><button class="close" data-close>×</button></div><form id="access-form" class="form"><div class="field"><label>Usuario</label><input name="usuario" placeholder="Tu usuario"></div><div class="field"><label>Clave</label><input name="clave" type="password" placeholder="Tu clave"></div><p id="access-message" class="message hidden"></p><button class="submit" style="background:linear-gradient(135deg,#4ade80,#22c55e)">Ingresar</button></form></section></aside>`;
  };

  const listEditor = (key, label, value) => { const rows = String(value || "").split("\n").map(x => x.trim()).filter(Boolean); const inputs = (rows.length ? rows : [""]).map(row => `<div class="grid2"><input data-list-input="${key}" value="${esc(row)}" placeholder="${label}"><button type="button" class="action" data-remove-entry="${key}">Quitar</button></div>`).join(""); return `<div class="field"><label>${label}</label><div data-list-box="${key}" class="form">${inputs}</div><input type="hidden" name="${key}" value="${esc(rows.join("\n"))}"><button type="button" class="action" data-add-entry="${key}" data-entry-label="${esc(label)}">+ Agregar ${label.toLowerCase()}</button></div>`; };
  const profileForm = (c) => `<div class="field"><label>Nombre</label><input name="nombre" value="${esc(c.nombre)}"></div><div class="grid2"><div class="field"><label>DNI</label><input name="dni" value="${esc(c.dni)}"></div><div class="field"><label>Teléfono</label><input name="telefono" value="${esc(c.telefono)}"></div></div><div class="field"><label>Dirección</label><input name="direccion" value="${esc(c.direccion)}"></div><div class="field"><label>Perfil público</label><textarea name="perfil">${esc(c.perfil)}</textarea></div>${listEditor("estudios", "Estudio", c.estudios)}${listEditor("experiencia", "Experiencia", c.experiencia)}`;
  const businessForm = (c) => `<div class="field"><label>Nombre del negocio</label><input name="negocio" value="${esc(c.negocio)}"></div><div class="grid2"><div class="field"><label>Giro</label><input name="giro" value="${esc(c.giro)}"></div><div class="field"><label>Teléfono</label><input name="telefono" value="${esc(c.telefono)}"></div></div><div class="field"><label>Dirección</label><input name="direccion" value="${esc(c.direccion)}"></div><div class="field"><label>Ubicación Google Maps</label><input name="maps" value="${esc(c.maps)}" placeholder="Pega el enlace de Google Maps"></div><div class="field"><label>Descripción</label><textarea name="perfil">${esc(c.perfil)}</textarea></div>`;
  const accountSheet = () => {
    const a = state.account || {}, c = a.client || {}, isBusiness = c.tipo_perfil === "NEGOCIO", pending = !c.activo;
    if (state.auth?.role === "admin") return adminSheet();
    return `<aside class="overlay open"><section class="sheet"><div class="sheet-head"><div><span class="eyebrow">MI WEBPOCKET</span><h3>${esc(c.nombre || c.negocio || state.auth?.client?.nombre || "Mi perfil")}</h3></div><button class="close" data-close>×</button></div>${pending ? '<p class="message">Tu cuenta está pendiente de validación manual de pago. Puedes guardar tus datos, pero tu perfil y QR público se activan después de la revisión.</p>' : '<p class="message ok">Tu cuenta está activa. Los cambios guardados permanecen disponibles para modificar cuando quieras.</p>'}<div class="menu centered"><button class="active" data-account-tab="profile">Perfil</button><button data-account-tab="media">Medios</button><button data-account-tab="questions">Preguntas</button><button data-account-tab="youtube">YouTube</button>${isBusiness ? '<button data-account-tab="products">Carrito</button>' : ''}<button data-account-tab="extras">Servicios</button><button data-account-tab="qr">QR</button></div><div id="account-body">${accountTab("profile")}</div></section></aside>`;
  };
  const accountTab = (tab) => {
    const a = state.account || {}, c = a.client || {}, isBusiness = c.tipo_perfil === "NEGOCIO";
    if (tab === "profile") return `<form id="profile-save-form" class="form">${isBusiness ? businessForm(c) : profileForm(c)}<div class="field"><label>Formato</label><select name="formatoId">${state.formats.map(f => `<option value="${esc(f.id)}" ${String(c.formato_id) === String(f.id) ? "selected" : ""}>${esc(f.nombre)}</option>`).join("")}</select></div><div class="colors"><div class="field"><label>Principal</label><input name="colorPrincipal" type="color" value="${esc(c.color_principal || "#38bdf8")}"></div><div class="field"><label>Secundario</label><input name="colorSecundario" type="color" value="${esc(c.color_secundario || "#a78bfa")}"></div><div class="field"><label>Fondo</label><input name="colorFondo" type="color" value="${esc(c.color_fondo || "#07101e")}"></div></div><button class="submit">Guardar datos del perfil</button></form>`;
    if (tab === "media") return `<div class="form"><p>Sube foto, video o CV. Cada archivo acepta hasta 15 MB. El video que subas queda pendiente para que el administrador lo apruebe o reemplace.</p><form id="media-form" class="form"><div class="field"><label>Tipo de archivo</label><select name="kind"><option value="foto">Foto de perfil</option><option value="video">Video</option>${!isBusiness ? '<option value="cv">Curriculum PDF</option>' : ''}</select></div><div class="field"><label>Archivo</label><input name="file" type="file" accept="image/*,video/mp4,video/webm,.pdf"></div><button class="submit">Subir archivo</button></form></div>`;
    if (tab === "questions") { const info = a.intelligence || [], ai = info.find(x => x.tipo_contenido === "CONFIGURACION_IA"), rows = info.filter(x => x.tipo_contenido === "PREGUNTA").map(x => `${x.pregunta || ""} | ${x.respuesta || ""}`).join("\n"); return `<form id="questions-form" class="form"><div class="field"><label>Modo</label><select name="mode"><option value="PRECONFIGURADA" ${ai ? "" : "selected"}>Preguntas predefinidas</option><option value="IA" ${ai ? "selected" : ""}>Preguntas por IA, S/ 10 adicional</option></select></div><div class="field"><label>Preguntas y respuestas</label><textarea name="questions" placeholder="Pregunta | Respuesta&#10;Puedes agregar varias líneas">${esc(rows)}</textarea></div><div class="field"><label>Conocimiento para IA</label><textarea name="knowledge" placeholder="Solo si eliges IA">${esc(ai?.conocimiento)}</textarea></div><div class="field"><label>Instrucciones para IA</label><textarea name="prompt" placeholder="Solo si eliges IA">${esc(ai?.prompt)}</textarea></div><button class="submit">Guardar preguntas</button></form>`; }
    if (tab === "youtube") { const links = (a.links || []).filter(x => x.tipo_enlace === "youtube").map(x => x.url || x.valor_enlace).join("\n"); return `<form id="youtube-form" class="form"><p>Agrega todos los videos de YouTube que necesites, uno por línea. Se mostrarán dentro de tu perfil.</p><div class="field"><label>Enlaces YouTube</label><textarea name="links" placeholder="https://www.youtube.com/watch?v=...">${esc(links)}</textarea></div><button class="submit">Guardar galería</button></form>`; }
    if (tab === "products") { const list = (a.products || []).map(x => `${x.descripcion || ""} | ${x.precio || 0} | ${x.stock || 0} | ${x.foto || ""}`).join("\n"); return `<form id="products-form" class="form"><p>El carrito cuesta S/ 10 e incluye hasta diez productos. Si necesitas más, solicita productos adicionales a S/ 5 cada uno.</p><div class="field"><label>Productos</label><textarea name="products" placeholder="Producto | Precio | Stock | URL de foto&#10;Un producto por línea">${esc(list)}</textarea></div><button class="submit">Guardar carrito</button></form>`; }
    if (tab === "extras") return `<form id="extra-form" class="form"><p>Solicita un servicio adicional y adjunta el comprobante para que el administrador lo revise.</p><div class="field"><label>Servicio</label><select name="type"><option value="VIDEO_DESDE_FOTO">Video creado desde foto, S/ 10</option><option value="CHAT_IA">Chat IA, S/ 10</option>${isBusiness ? '<option value="CARRITO">Carrito hasta 10 productos, S/ 10</option><option value="PRODUCTOS_ADICIONALES">Productos adicionales, S/ 5 c/u</option>' : ''}</select></div><div class="field"><label>Cantidad adicional</label><input name="quantity" type="number" min="1" value="1"></div><div class="field"><label>Comprobante</label><input name="receipt" type="file" accept="image/*,.pdf"></div><button class="submit">Enviar solicitud adicional</button></form>`;
    const qr = a.qr || {}, publicUrl = c.activo ? `${location.origin}${location.pathname}?perfil=${encodeURIComponent(c.codigo_cliente)}` : ""; return `<div class="form"><p>${c.activo ? "Tu perfil está activo. Comparte tu enlace o descarga el QR." : "El QR propio se activa luego de la validación manual del pago."}</p><div class="card"><b>Código</b><p>${esc(qr.codigo_qr || c.codigo_cliente || "Pendiente")}</p></div><div class="card"><b>Enlace</b><p>${esc(publicUrl || "Pendiente de activación")}</p></div>${publicUrl ? `<img alt="QR de tu WebPocket" style="width:190px;border-radius:14px;background:#fff;padding:8px" src="https://api.qrserver.com/v1/create-qr-code/?size=260x260&data=${encodeURIComponent(publicUrl)}"><a class="submit" href="https://api.qrserver.com/v1/create-qr-code/?size=1000x1000&data=${encodeURIComponent(publicUrl)}" download="webpocket-qr.png">Descargar mi QR</a>` : ""}</div>`;
  };
  const adminSheet = () => { const a = state.account || {}, clients = a.clients || [], payments = a.payments || []; return `<aside class="overlay open"><section class="sheet"><div class="sheet-head"><div><span class="eyebrow">ADMINISTRACIÓN</span><h3>Pagos, clientes y precios</h3></div><button class="close" data-close>×</button></div><p>Revisa el comprobante, activa el cliente y sube el video aprobado desde aquí.</p><div class="card-list">${clients.map(c => `<article class="card"><b>${esc(c.nombre || c.negocio || c.usuario)} · ${esc(c.codigo_cliente)}</b><p>${c.activo ? "Activo" : "Pendiente"} · ${esc(c.tipo_perfil)}</p><div class="grid2"><button class="action" data-activate="${esc(c.codigo_cliente)}" data-active="${c.activo ? "0" : "1"}">${c.activo ? "Desactivar" : "Activar tras validar pago"}</button><button class="action" data-admin-video="${esc(c.codigo_cliente)}">Subir video aprobado</button></div></article>`).join("") || "<p>No hay clientes.</p>"}</div><form id="admin-video-form" class="form hidden"><div class="field"><label>Video aprobado</label><input name="file" type="file" accept="video/mp4,video/webm"></div><input name="codigoCliente" type="hidden"><button class="submit">Guardar video para cliente</button></form><h3 style="margin-top:16px">Comprobantes</h3><div class="card-list">${payments.map(p => `<article class="card"><b>${esc(p.codigo_cliente)} · S/ ${Number(p.importe || 0).toFixed(2)}</b><p>${esc(p.estado_pago)}</p>${p.url_comprobante ? `<a href="${esc(p.url_comprobante)}" target="_blank" rel="noreferrer">Ver o descargar comprobante</a>` : ""}${String(p.estado_pago || "").startsWith("PENDIENTE_") ? `<button class="action" data-extra-approve="${esc(p.codigo_cliente)}" data-extra-type="${esc(p.estado_pago)}">Aprobar servicio adicional</button>` : ""}</article>`).join("")}</div><h3 style="margin-top:16px">Precios de servicios</h3><form id="plans-form" class="form">${(a.plans || []).map(p => `<div class="card"><b>${esc(p.nombre)} · ${p.duracion_meses} meses</b><div class="grid2"><div class="field"><label>Base</label><input name="base-${esc(p.id)}" type="number" value="${Number(p.precio_base || 0)}"></div><div class="field"><label>IA</label><input name="ia-${esc(p.id)}" type="number" value="${Number(p.precio_ia || 10)}"></div><div class="field"><label>Carrito</label><input name="cart-${esc(p.id)}" type="number" value="${Number(p.precio_carrito || 10)}"></div><div class="field"><label>Producto adicional</label><input name="product-${esc(p.id)}" type="number" value="${Number(p.precio_producto_adicional || 5)}"></div></div></div>`).join("")}<button class="submit">Guardar precios</button></form></section></aside>`; };

  window.renderPanel = function (p) { if (state.panel === "account") return accountSheet(); return basePanel(p); };
  window.bind = function () {
    baseBind();
    const quick = app.querySelector("#quick-register-form"); if (quick) { const updatePrice = () => { const type = quick.elements.tipoPerfil.value, months = Number(quick.elements.periodoMeses.value), plan = state.plans.find(p => String(p.tipo_perfil).toUpperCase() === type && Number(p.duracion_meses) === months), fallback = type === "CV" ? ({3:40,6:50,12:80}[months]) : ({3:50,6:80,12:100}[months]), total = Number(plan?.precio_base ?? fallback); app.querySelector("#quick-total").textContent = `S/ ${total.toFixed(2)}`; app.querySelector("#quick-detail").textContent = `${type === "CV" ? "CV virtual" : "Negocio Pocket"} por ${months} meses. Yape: 967 188 120.`; }; quick.elements.tipoPerfil.addEventListener("change", updatePrice); quick.elements.periodoMeses.addEventListener("change", updatePrice); updatePrice(); quick.addEventListener("submit", async e => { e.preventDefault(); const form = e.currentTarget, fd = new FormData(form); try { notice("#quick-register-message", "Subiendo comprobante…"); const file = fd.get("receipt"); const uploaded = await edge({ action: "upload_receipt", fileData: await readDataUrl(file), fileName: file.name }); const result = await edge({ action: "register", registration: { usuario: fd.get("usuario"), clave: fd.get("clave"), tipoPerfil: fd.get("tipoPerfil"), periodoMeses: Number(fd.get("periodoMeses")), formatoId: fd.get("formatoId"), colores: { principal: fd.get("principal"), secundario: fd.get("secundario"), fondo: fd.get("fondo") }, receipt: uploaded.file } }); notice("#quick-register-message", `Solicitud registrada. Código ${result.codigoCliente}. Espera la validación manual del pago.`, "ok"); } catch (error) { notice("#quick-register-message", error.message, "error"); } }); }
    app.querySelector("#access-form")?.addEventListener("submit", async e => { e.preventDefault(); const fd = new FormData(e.currentTarget); try { const result = await edge({ action: "login", usuario: fd.get("usuario"), clave: fd.get("clave") }); state.auth = result; state.account = result.role === "admin" ? await send({ action: "admin_get" }) : await send({ action: "client_get" }); state.panel = "account"; render(); } catch (error) { notice("#access-message", error.message, "error"); } });
    app.querySelectorAll("[data-account-tab]").forEach(button => button.addEventListener("click", () => { const body = app.querySelector("#account-body"); if (body) body.innerHTML = accountTab(button.dataset.accountTab); bind(); }));
    app.querySelectorAll("[data-add-entry]").forEach(button => button.addEventListener("click", () => { const key = button.dataset.addEntry, label = button.dataset.entryLabel, box = app.querySelector(`[data-list-box="${key}"]`), row = document.createElement("div"); row.className = "grid2"; row.innerHTML = `<input data-list-input="${key}" placeholder="${esc(label)}"><button type="button" class="action" data-remove-entry="${key}">Quitar</button>`; box.appendChild(row); bind(); }));
    app.querySelectorAll("[data-remove-entry]").forEach(button => button.addEventListener("click", () => { const box = button.closest("[data-list-box]"); if (box && box.children.length > 1) button.parentElement.remove(); else if (button.parentElement?.querySelector("input")) button.parentElement.querySelector("input").value = ""; }));
    app.querySelector("#profile-save-form")?.addEventListener("submit", async e => { e.preventDefault(); const form = e.currentTarget; ["estudios", "experiencia"].forEach(key => { const hidden = form.querySelector(`[name="${key}"]`); if (hidden) hidden.value = [...form.querySelectorAll(`[data-list-input="${key}"]`)].map(input => input.value.trim()).filter(Boolean).join("\n"); }); const fd = new FormData(form); try { await send({ action: "client_save", profile: Object.fromEntries(fd) }); alert("Datos guardados. Permanecerán aquí para que puedas modificarlos cuando quieras."); } catch (error) { alert(error.message); } });
    app.querySelector("#media-form")?.addEventListener("submit", async e => { e.preventDefault(); const fd = new FormData(e.currentTarget), file = fd.get("file"); try { await send({ action: "client_upload", kind: fd.get("kind"), fileData: await readDataUrl(file), fileName: file.name }); alert("Archivo guardado."); } catch (error) { alert(error.message); } });
    app.querySelector("#questions-form")?.addEventListener("submit", async e => { e.preventDefault(); const fd = new FormData(e.currentTarget), rows = String(fd.get("questions") || "").split("\n").map(line => { const [pregunta, respuesta] = line.split("|"); return { pregunta: pregunta?.trim(), respuesta: respuesta?.trim() }; }); try { await send({ action: "client_save_questions", mode: fd.get("mode"), questions: rows, knowledge: fd.get("knowledge"), prompt: fd.get("prompt") }); alert("Preguntas guardadas."); } catch (error) { alert(error.message); } });
    app.querySelector("#youtube-form")?.addEventListener("submit", async e => { e.preventDefault(); const fd = new FormData(e.currentTarget); try { await send({ action: "client_save_youtube", links: String(fd.get("links") || "").split(/\n|,/).map(x => x.trim()).filter(Boolean) }); alert("Galería guardada."); } catch (error) { alert(error.message); } });
    app.querySelector("#products-form")?.addEventListener("submit", async e => { e.preventDefault(); const fd = new FormData(e.currentTarget), products = String(fd.get("products") || "").split("\n").map(line => { const [descripcion, precio, stock, foto] = line.split("|"); return { descripcion: descripcion?.trim(), precio: Number(precio), stock: Number(stock), foto: foto?.trim() }; }); try { await send({ action: "client_save_products", products }); alert("Carrito guardado."); } catch (error) { alert(error.message); } });
    app.querySelector("#extra-form")?.addEventListener("submit", async e => { e.preventDefault(); const fd = new FormData(e.currentTarget), file = fd.get("receipt"); try { const uploaded = await edge({ action: "upload_receipt", fileData: await readDataUrl(file), fileName: file.name }); const result = await send({ action: "request_extra", type: fd.get("type"), quantity: fd.get("quantity"), receipt: uploaded.file }); alert(`Solicitud enviada. Importe: S/ ${Number(result.importe).toFixed(2)}`); } catch (error) { alert(error.message); } });
    app.querySelectorAll("[data-activate]").forEach(button => button.addEventListener("click", async () => { try { await send({ action: "admin_activate", codigoCliente: button.dataset.activate, active: button.dataset.active === "1" }); state.account = await send({ action: "admin_get" }); render(); } catch (error) { alert(error.message); } }));
    app.querySelectorAll("[data-extra-approve]").forEach(button => button.addEventListener("click", async () => { try { await send({ action: "admin_approve_extra", codigoCliente: button.dataset.extraApprove, type: button.dataset.extraType }); state.account = await send({ action: "admin_get" }); render(); } catch (error) { alert(error.message); } }));
    app.querySelectorAll("[data-admin-video]").forEach(button => button.addEventListener("click", () => { const form = app.querySelector("#admin-video-form"); form.classList.remove("hidden"); form.elements.codigoCliente.value = button.dataset.adminVideo; form.scrollIntoView({ behavior: "smooth" }); }));
    app.querySelector("#admin-video-form")?.addEventListener("submit", async e => { e.preventDefault(); const fd = new FormData(e.currentTarget), file = fd.get("file"); try { await send({ action: "admin_video", codigoCliente: fd.get("codigoCliente"), fileData: await readDataUrl(file), fileName: file.name }); alert("Video aprobado guardado."); } catch (error) { alert(error.message); } });
    app.querySelector("#plans-form")?.addEventListener("submit", async e => { e.preventDefault(); const fd = new FormData(e.currentTarget), list = (state.account?.plans || []).map(p => ({ ...p, precio_base: Number(fd.get(`base-${p.id}`)), precio_ia: Number(fd.get(`ia-${p.id}`)), precio_carrito: Number(fd.get(`cart-${p.id}`)), precio_producto_adicional: Number(fd.get(`product-${p.id}`)) })); try { await send({ action: "admin_plans", plans: list }); alert("Precios guardados."); } catch (error) { alert(error.message); } });
  };
})();
